### ISSUE TITLE
{HYPEREXECUTE}-How can I dynamically assign a value to the name of uploaded artifacts, where the value is derived from system environment variable?

### ISSUE THREAD

**Issue by devusecases** [devusecases/Hyperexecute-Discussion#2]
How can I dynamically assign a value to the name of uploaded artifacts, ensuring that the name is retrieved from a system environment variable at runtime?

Currently I am using like this
```

uploadArtefacts:
  - name: "Reports"
    path:
    - reports/**.  
```

**Comment by shubhamsinghrathore** [comment]
You can achieve this by using `${your_variable}.` In your case, it would be:

```
uploadArtefacts:
  - name: "${abcd}"
    path:
    - reports/** 
```
if value of `abcd = Folder `then it will come something like `Artefacts Folder `on Hyperexecute dashboard.

**Comment by vishnukdas** [comment]
@shubhamsinghrathore how do I pass value to this variable? 
Also, I have a github actions setup to trigger my job, how can I use the artefact name from my github env variable to the hyperexecute YAML.

**Comment by shubhamsinghrathore** [comment]
@vishnukdas 

how do I pass value to this variable? You can pass value env value with the help of this param `--vars` in hyperexecute CLI  command like:
 ./hyperexecute --user <username>--key<accesskey> --config <pathofyouryaml> --vars  key=value


Add the key in env block of the yaml so we can exposed the variable in HyperExecute vm's:
```
env:
  abcde: ${key}
```

`
I have a github actions setup to trigger my job, how can I use the artefact name from my github env variable to the hyperexecute YAML?`


Sample githubactions pipeline yaml:

```
name: Run HyperExecute Job

on:
  push:
    branches:
      - main

jobs:
  run-hyperexecute:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Environment Variables
        run: |
          echo "HYPEREXECUTE_USER=<username>" >> $GITHUB_ENV
          echo "HYPEREXECUTE_KEY=<accesskey>" >> $GITHUB_ENV
          echo "CONFIG_PATH=<pathofyouryaml>" >> $GITHUB_ENV
          echo "VAR_KEY=value" >> $GITHUB_ENV

      - name: Install HyperExecute CLI
        run: |
          curl -o https://downloads.lambdatest.com/hyperexecute/linux/hyperexecute
          chmod u+x ./hyperexecute
      
      - name: Run HyperExecute
        run: |
          ./hyperexecute --user $HYPEREXECUTE_USER --key $HYPEREXECUTE_KEY --config $CONFIG_PATH --vars key=$VAR_KEY


```

Once the value is exposed in VM then you are able to use that in upload artifacts as well for labelling or name.


Let me know if it works.
