### ISSUE TITLE
How to configure native Extent Reports in Java TestNG with AventStack Plugin (version 3.0.0) and integrate it with HyperExecute for report visualization on HyperExecute UI?

### ISSUE THREAD

**Issue by devusecases** [devusecases/Hyperexecute-Discussion#4]
I am currently working with a Java TestNG framework and using the AventStack Extent Reports plugin (version 3.0.0) to generate comprehensive test execution reports. Additionally, I am running my test jobs on HyperExecute and would like to know how to configure the native Extent Reports within my Java framework and also integrate it with HyperExecute, so that I can view the reports directly on the HyperExecute UI after my test job execution.

Currently I am passing report config something like this in the hyperexecute yaml

```
report: true
partialReports:
 type: html
 location: reports/htmlReports
 frameworkName: extent
```

But unable to get report, though my report is created in html as well as json

**Comment by shubhamsinghrathore** [comment]
To generate a report, we need to make sure we can generate JSON reports in the report folder by including the following parameter in YAML:

```
report: true
partialReports:
  type: json
  location: reports/htmlReports
  frameworkName: extent-native
```

My JSON file was created in `reports/htmlReports.`
