### ISSUE TITLE
How to check tunnel health during HyperExecute tests and auto-retry if it stops?"

### ISSUE THREAD

**Issue by devusecases** [devusecases/Hyperexecute-Discussion#7]
I am using HyperExecute for running my automated tests, but I have encountered issues where the tunnel connection drops or becomes unstable during test execution, leading to failures in connecting to the remote devices or environments. I want to configure a mechanism that allows me to:

```
Monitoring Tunnel Health: How can I check if the tunnel is active during test execution and detect if it stops working?

Auto-Retry on Tunnel Failure: How can I automatically retry the tunnel connection if it drops during test execution, without manual intervention? What’s the best way to set up this auto-retry mechanism?

Integration with Test Execution: How can I integrate tunnel health checks and retries directly into my HyperExecute test pipeline?
```

Any suggestions or examples on implementing this would be appreciated!

currently my yaml looks like this:

````
---
version: "0.1"
globalTimeout: 90
testSuiteTimeout: 90
testSuiteStep: 90
runson: win
autosplit: true
retryOnFailure: false
maxRetries: 1
concurrency: 1


tunnel: true

runtime:
  - language: node
    version: "18"
pre:
  - node -v
  - npm install
  
  
  
cacheKey: '{{ checksum "package-lock.json" }}'
cacheDirectories:
  - node_modules



testDiscovery:
  type: raw
  mode: static
  command: ls e2e/tests/quotes

testRunnerCommand:   npx playwright test e2e/tests/quotes/$test


jobLabel: [playwright-CodeceptJS, win, autosplit] 
```
